import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { useParams } from 'react-router-dom';
import { z } from 'zod';
import { bankApi } from '../shared/api/bank';
import { ErrorState, LoadingState } from '../shared/components/State';
import { date, money } from '../shared/lib/utils';
const schema=z.object({amount:z.coerce.number().positive('Введите сумму')}); type FormInput=z.input<typeof schema>; type Form=z.output<typeof schema>;
export function AccountDetailsPage(){const {id=''}=useParams(); const qc=useQueryClient(); const account=useQuery({queryKey:['account',id],queryFn:()=>bankApi.account(id)}); const tx=useQuery({queryKey:['accountTx',id],queryFn:()=>bankApi.accountTransactions(id)}); const form=useForm<FormInput, unknown, Form>({resolver:zodResolver(schema)}); const mutate=useMutation({mutationFn:({kind,amount}:{kind:'topUp'|'withdraw';amount:number})=>kind==='topUp'?bankApi.topUp(Number(id),amount):bankApi.withdraw(Number(id),amount),onSuccess:()=>{qc.invalidateQueries(); form.reset();}}); if(account.isLoading)return <LoadingState/>; if(account.error)return <ErrorState error={account.error}/>; const a=account.data!; return <div className="space-y-6"><div className="card"><span className="badge">{a.type}</span><h2 className="mt-4 text-5xl font-black">{money(a.balance,a.currency)}</h2><p className="mt-2 text-black/50">{a.iban}</p></div><form className="card grid gap-3 sm:grid-cols-[1fr_auto_auto]" onSubmit={e=>e.preventDefault()}><input className="input" placeholder="Сумма" {...form.register('amount')}/><button className="btn-secondary" onClick={form.handleSubmit(d=>mutate.mutate({kind:'topUp',amount:d.amount}))}>Пополнить</button><button className="btn" onClick={form.handleSubmit(d=>{if(confirm('Списать средства?'))mutate.mutate({kind:'withdraw',amount:d.amount})})}>Списать</button><p className="text-red-600">{form.formState.errors.amount?.message}</p></form><div className="card"><h3 className="mb-4 text-xl font-black">Операции счета</h3><div className="space-y-2">{tx.data?.map(t=><div key={t.id} className="flex justify-between rounded-2xl bg-black/5 p-3"><span>{t.description||t.type}<br/><small>{date(t.createdAt)}</small></span><b>{money(t.amount,a.currency)}</b></div>)}</div></div></div>}
