import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { bankApi } from '../shared/api/bank';
import { Field } from './LoginPage';
import { EstimateCard, money } from './LoanApplicationPage';
const products = [{ name: 'Boys Classic', text: 'Баланс ставки и гибкости.' }, { name: 'Boys Max', text: 'Повышенная ставка при фиксированном сроке.' }, { name: 'Boys Flex', text: 'Опция досрочного доступа к деньгам.' }];
const schema = z.object({ sourceAccountId: z.coerce.number().positive(), amount: z.coerce.number().min(1000), termMonths: z.coerce.number().min(1).max(120), productName: z.string(), capitalization: z.boolean().optional(), earlyWithdrawal: z.boolean().optional() }); type FormInput = z.input<typeof schema>; type Form = z.output<typeof schema>;
export function DepositApplicationPage() { const accounts = useQuery({ queryKey: ['accounts'], queryFn: bankApi.accounts }); const nav = useNavigate(); const form = useForm<FormInput, unknown, Form>({ resolver: zodResolver(schema), defaultValues: { termMonths: 12, productName: 'Boys Classic', capitalization: false, earlyWithdrawal: false } }); const amount = Number(form.watch('amount')); const termMonths = Number(form.watch('termMonths')); const estimate = useQuery({ queryKey: ['depositEstimate', amount, termMonths], queryFn: () => bankApi.depositEstimate(amount, termMonths), enabled: amount >= 1000 && termMonths >= 1 && termMonths <= 120 }); const mutation = useMutation({ mutationFn: bankApi.applyDeposit, onSuccess: () => nav('/deposits') });
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="card max-w-2xl"><h2 className="mb-5 text-3xl font-black">Открыть вклад</h2><div className="mb-5 grid gap-3 md:grid-cols-3">{products.map((p) => <button type="button" className={`rounded-3xl border p-4 text-left ${form.watch('productName') === p.name ? 'border-ink bg-fintech' : 'border-black/10'}`} key={p.name} onClick={() => form.setValue('productName', p.name)}><b>{p.name}</b><p className="mt-2 text-xs text-black/55">{p.text}</p></button>)}</div><form className="space-y-4" onSubmit={form.handleSubmit((d) => mutation.mutate(d))}><Field label="Счет списания"><select className="input" {...form.register('sourceAccountId')}><option value="">Выберите</option>{accounts.data?.map((a) => <option value={a.id} key={a.id}>{a.iban} · {money(a.balance)}</option>)}</select></Field><Field label="Сумма"><input className="input" {...form.register('amount')} /></Field><Field label="Срок, мес"><input className="input" {...form.register('termMonths')} /></Field><label className="flex gap-3 rounded-2xl bg-black/5 p-3"><input type="checkbox" {...form.register('capitalization')} /> Капитализировать проценты</label><label className="flex gap-3 rounded-2xl bg-black/5 p-3"><input type="checkbox" {...form.register('earlyWithdrawal')} /> Нужна опция досрочного снятия</label><p className="rounded-2xl bg-black/5 p-4 text-sm text-black/60">Ставка подтягивается из условий банка и корректируется по выбранному продукту.</p>{mutation.error && <p className="text-red-600">{mutation.error.message}</p>}<button className="btn">Открыть вклад</button></form></div><EstimateCard title="Доход по вкладу" loading={estimate.isFetching} items={estimate.data ? [['Ставка банка', `${estimate.data.annualRate}%`], ['Дата окончания', new Date(estimate.data.maturityDate).toLocaleDateString('ru-RU')], ['Доход', money(estimate.data.income)], ['К выплате', money(estimate.data.projectedPayout)]] : []} /></div>; }
