import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { authApi } from '../features/auth/api';
import { useAuthStore } from '../features/auth/store';
const schema = z.object({ email: z.string().email('Введите email'), password: z.string().min(6, 'Минимум 6 символов') });
type Form = z.infer<typeof schema>;
export function LoginPage() { const setToken = useAuthStore(s=>s.setToken); const navigate=useNavigate(); const { register, handleSubmit, formState:{errors,isSubmitting}, setError, setValue }=useForm<Form>({resolver:zodResolver(schema), defaultValues:{email:'demo@boys.bank', password:'password'}}); return <AuthShell title="Вход в банк" subtitle="Demo: demo@boys.bank / password · Admin: admin@boys.bank / password"><form className="space-y-4" onSubmit={handleSubmit(async data=>{try{const res=await authApi.login(data); setToken(res.token); navigate('/dashboard');}catch(e){setError('root',{message:e instanceof Error?e.message:'Ошибка входа'});}})}><Field label="Email" error={errors.email?.message}><input className="input" {...register('email')} /></Field><Field label="Пароль" error={errors.password?.message}><input className="input" type="password" {...register('password')} /></Field>{errors.root && <p className="text-sm text-red-600">{errors.root.message}</p>}<div className="grid gap-2 sm:grid-cols-2"><button type="button" className="btn-secondary" onClick={()=>{setValue('email','demo@boys.bank'); setValue('password','password')}}>Demo user</button><button type="button" className="btn-secondary" onClick={()=>{setValue('email','admin@boys.bank'); setValue('password','password')}}>Admin</button></div><button disabled={isSubmitting} className="btn w-full">Войти</button><p className="text-center text-sm">Нет аккаунта? <Link className="font-bold underline" to="/register">Регистрация</Link></p></form></AuthShell> }
export function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="grid min-h-screen place-items-center bg-[#f7f7f3] p-4"><section className="grid w-full max-w-5xl overflow-hidden rounded-[2rem] bg-white shadow-soft md:grid-cols-2"><div className="bg-ink p-10 text-white"><div className="mb-20 inline-flex rounded-2xl bg-fintech px-4 py-3 font-black text-ink">Boys Bank</div><h1 className="text-4xl font-black">{title}</h1><p className="mt-4 text-white/65">{subtitle}</p></div><div className="p-8 md:p-10">{children}</div></section></main>}
export function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="label">{label}</span>{children}{error && <span className="text-sm text-red-600">{error}</span>}</label>}
