import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { bankApi } from '../shared/api/bank';
import { Field } from './LoginPage';
import { newOperationId } from '../shared/lib/utils';
const schema=z.object({fromAccountId:z.coerce.number().positive(),toIban:z.string().min(8,'Введите IBAN'),amount:z.coerce.number().positive('Введите сумму'),description:z.string().optional()}); type Form=z.infer<typeof schema>;
export function TransferPage(){const accounts=useQuery({queryKey:['accounts'],queryFn:bankApi.accounts}); const form=useForm<Form>({resolver:zodResolver(schema)}); const m=useMutation({mutationFn:(d:Form)=>bankApi.transfer({...d,operationId:newOperationId()}),onSuccess:()=>form.reset()}); return <div className="card max-w-2xl"><h2 className="mb-5 text-3xl font-black">Новый перевод</h2><form className="space-y-4" onSubmit={form.handleSubmit(d=>m.mutate(d))}><Field label="Счет списания" error={form.formState.errors.fromAccountId?.message}><select className="input" {...form.register('fromAccountId')}><option value="">Выберите</option>{accounts.data?.map(a=><option value={a.id} key={a.id}>{a.iban} · {a.balance} {a.currency}</option>)}</select></Field><Field label="IBAN получателя" error={form.formState.errors.toIban?.message}><input className="input" {...form.register('toIban')}/></Field><Field label="Сумма" error={form.formState.errors.amount?.message}><input className="input" {...form.register('amount')}/></Field><Field label="Назначение"><input className="input" {...form.register('description')}/></Field>{m.error&&<p className="text-red-600">{m.error.message}</p>}{m.isSuccess&&<p className="text-green-700">Перевод выполнен</p>}<button className="btn">Отправить</button></form></div>}
