import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Repeat, ShieldCheck, Users } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { bankApi } from '../shared/api/bank';
import { newOperationId } from '../shared/lib/utils';
import { Field } from './LoginPage';
const schema = z.object({ fromAccountId: z.coerce.number().positive(), toIban: z.string().min(8, 'Введите IBAN'), amount: z.coerce.number().positive('Введите сумму'), description: z.string().optional() }); type FormInput = z.input<typeof schema>; type Form = z.output<typeof schema>;
const templates = [{ title: 'Себе между счетами', icon: Repeat, text: 'Укажите IBAN своего второго счета.' }, { title: 'Родным и друзьям', icon: Users, text: 'Добавьте назначение — получателю будет понятнее.' }, { title: 'Крупный платеж', icon: ShieldCheck, text: 'Проверьте лимиты и описание перед отправкой.' }];
export function TransferPage() {
  const accounts = useQuery({ queryKey: ['accounts'], queryFn: bankApi.accounts }); const form = useForm<FormInput, unknown, Form>({ resolver: zodResolver(schema) }); const selected = accounts.data?.find((a) => a.id === Number(form.watch('fromAccountId')));
  const m = useMutation({ mutationFn: (d: Form) => bankApi.transfer({ ...d, operationId: newOperationId() }), onSuccess: () => form.reset() });
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="card"><h2 className="mb-2 text-3xl font-black">Новый перевод</h2><p className="mb-5 text-black/55">Заполните перевод, используйте шаблоны и контролируйте остаток до отправки.</p><form className="space-y-4" onSubmit={form.handleSubmit((d) => m.mutate(d))}><Field label="Счет списания" error={form.formState.errors.fromAccountId?.message}><select className="input" {...form.register('fromAccountId')}><option value="">Выберите</option>{accounts.data?.map((a) => <option value={a.id} key={a.id}>{a.iban} · {a.balance} {a.currency}</option>)}</select></Field><Field label="IBAN получателя" error={form.formState.errors.toIban?.message}><input className="input" {...form.register('toIban')} /></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Сумма" error={form.formState.errors.amount?.message}><input className="input" {...form.register('amount')} /></Field><Field label="Назначение"><input className="input" placeholder="Например: аренда, подарок" {...form.register('description')} /></Field></div>{selected && <p className="rounded-2xl bg-black/5 p-4 text-sm text-black/60">После перевода доступный остаток рассчитывается со счета {selected.productName ?? selected.type}. Текущий баланс: {selected.balance} {selected.currency}.</p>}{m.error && <p className="text-red-600">{m.error.message}</p>}{m.isSuccess && <p className="text-green-700">Перевод выполнен</p>}<button className="btn">Отправить</button></form></div><aside className="space-y-4"><div className="card bg-fintech"><h3 className="text-xl font-black">Шаблоны и сценарии</h3><div className="mt-4 space-y-3">{templates.map(({ icon: Icon, ...t }) => <div className="rounded-3xl bg-white/70 p-4" key={t.title}><Icon className="mb-2 h-5 w-5" /><b>{t.title}</b><p className="mt-1 text-sm text-black/55">{t.text}</p></div>)}</div></div><div className="card"><b>Антифрод-чек</b><p className="mt-2 text-sm text-black/55">Для новых IBAN добавляйте понятное назначение. Это снижает шанс ручной проверки и помогает в истории операций.</p></div></aside></div>;
}
