import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { bankApi } from '../shared/api/bank';
import { EmptyState, ErrorState, LoadingState } from '../shared/components/State';
import { date, money } from '../shared/lib/utils';
export function TransactionsPage() {
  const [query, setQuery] = useState(''); const [type, setType] = useState('ALL'); const q = useQuery({ queryKey: ['transactions'], queryFn: bankApi.transactions });
  const filtered = useMemo(() => (q.data ?? []).filter((t) => (type === 'ALL' || t.type === type) && `${t.description ?? ''} ${t.operationId}`.toLowerCase().includes(query.toLowerCase())), [q.data, query, type]);
  if (q.isLoading) return <LoadingState />; if (q.error) return <ErrorState error={q.error} />;
  const total = filtered.reduce((sum, t) => sum + Number(t.amount), 0); const avg = filtered.length ? total / filtered.length : 0; const largest = Math.max(0, ...filtered.map((t) => Number(t.amount)));
  return <div className="space-y-5"><div><h2 className="text-3xl font-black">Операции</h2><p className="mt-2 text-black/55">История дополнена поиском, фильтрами, сводкой и быстрым аудитом платежей.</p></div><section className="grid gap-3 md:grid-cols-3"><Kpi title="Операций" value={String(filtered.length)} /><Kpi title="Сумма выборки" value={money(total)} /><Kpi title="Средний чек" value={money(avg)} /></section><div className="card"><div className="mb-5 grid gap-3 md:grid-cols-[1fr_220px_180px]"><label className="relative"><Search className="absolute left-4 top-3.5 h-4 w-4 text-black/40" /><input className="input pl-10" placeholder="Поиск по назначению или ID" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select className="input" value={type} onChange={(e) => setType(e.target.value)}><option value="ALL">Все типы</option><option value="TRANSFER">Переводы</option><option value="DONATION">Донаты</option><option value="DEPOSIT_OPEN">Вклады</option><option value="ADJUSTMENT">Корректировки</option></select><div className="rounded-2xl bg-fintech p-3 text-sm font-bold">Максимум: {money(largest)}</div></div>{!filtered.length ? <EmptyState /> : <div className="overflow-x-auto"><table className="w-full text-left"><tbody>{filtered.map((t) => <tr className="border-t" key={t.id}><td className="py-4"><b>{t.description || t.type}</b><p className="text-sm text-black/50">{date(t.createdAt)} · {t.operationId}</p></td><td><span className="badge">{t.type}</span></td><td>{t.fromAccountId ?? '—'} → {t.toAccountId ?? '—'}</td><td className="text-right font-black">{money(t.amount)}</td></tr>)}</tbody></table></div>}</div></div>;
}
function Kpi({ title, value }: { title: string; value: string }) { return <div className="card"><p className="text-sm text-black/50">{title}</p><b className="mt-2 block text-2xl">{value}</b></div>; }
