import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Banknote, CreditCard, Gauge, Landmark, LogOut, ShieldAlert, User, WalletCards } from 'lucide-react';
import { useAuthStore } from '../../features/auth/store';
const nav = [
  ['/dashboard','Обзор',Gauge], ['/accounts','Счета',WalletCards], ['/transactions','Операции',Banknote], ['/transfers/new','Перевод',Landmark], ['/cards','Карты',CreditCard], ['/loans','Кредиты',Landmark], ['/deposits','Вклады',WalletCards], ['/fraud','Антифрод',ShieldAlert], ['/profile','Профиль',User]
] as const;
export function AppLayout() {
  const { user, logout } = useAuthStore(); const navigate = useNavigate(); const isAdmin = user?.roles?.includes('ADMIN');
  return <div className="min-h-screen bg-[#f7f7f3]"><aside className="fixed inset-y-0 left-0 hidden w-72 flex-col border-r border-black/5 bg-white/80 p-5 backdrop-blur lg:flex"><Link to="/dashboard" className="mb-8 flex items-center gap-3 text-2xl font-black"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-fintech">BB</span>Boys Bank</Link><nav className="space-y-1">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} className={({isActive})=>`flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold ${isActive?'bg-ink text-white':'text-black/65 hover:bg-black/5'}`}><Icon className="h-4 w-4"/>{label}</NavLink>)}{isAdmin && <NavLink to="/admin" className={({isActive})=>`flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold ${isActive?'bg-ink text-white':'text-black/65 hover:bg-black/5'}`}>Admin</NavLink>}</nav><button className="btn mt-auto" onClick={()=>{logout(); navigate('/login')}}><LogOut className="mr-2 h-4 w-4"/>Выйти</button></aside><main className="lg:pl-72"><header className="sticky top-0 z-10 border-b border-black/5 bg-[#f7f7f3]/80 px-4 py-4 backdrop-blur lg:px-10"><div className="flex items-center justify-between"><div><p className="text-sm text-black/50">Добро пожаловать</p><h1 className="text-xl font-black">{user ? `${user.firstName} ${user.lastName}` : 'Boys Bank'}</h1></div><div className="badge">{user?.roles?.join(', ')}</div></div><nav className="mt-3 flex gap-2 overflow-x-auto lg:hidden">{nav.map(([to,label])=><NavLink className="badge whitespace-nowrap" to={to} key={to}>{label}</NavLink>)}{isAdmin && <NavLink className="badge whitespace-nowrap" to="/admin" key="/admin">Admin</NavLink>}</nav></header><section className="p-4 lg:p-10"><Outlet/></section></main></div>;
}
